# Generated by Django 5.1.6 on 2025-03-15 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_description_band_sold_band_type_band_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sold', models.BooleanField(default=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.band')),
            ],
        ),
    ]
