# Generated by Django 5.1.6 on 2025-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='description',
        ),
        migrations.RemoveField(
            model_name='band',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='band',
            name='type',
        ),
        migrations.RemoveField(
            model_name='band',
            name='year',
        ),
        migrations.AlterField(
            model_name='band',
            name='biography',
            field=models.TextField(default='No Biography available'),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock')], default='HH', max_length=20),
        ),
        migrations.AlterField(
            model_name='band',
            name='official_homepage',
            field=models.URLField(blank=True, default=''),
        ),
    ]
